;/*FB_PKG_DELIM*/

__d("GroupsCometNotificationSettingsEditDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="6027217000728024"}),null);
__d("GroupsCometNotificationSettingsEditDialogQuery$Parameters",["GroupsCometNotificationSettingsEditDialogQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("GroupsCometNotificationSettingsEditDialogQuery_facebookRelayOperation"),metadata:{},name:"GroupsCometNotificationSettingsEditDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("GroupsCometManageNotificationsActionMenuItem_group$normalization.graphql",[],(function(a,b,c,d,e,f){"use strict";a={kind:"SplitOperation",metadata:{},name:"GroupsCometManageNotificationsActionMenuItem_group$normalization",selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}]};e.exports=a}),null);
__d("GroupsCometManageNotificationsActionMenuItem_group.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"GroupsCometManageNotificationsActionMenuItem_group",selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}],type:"Group",abstractKey:null};e.exports=a}),null);
__d("GroupCometCreationTooltipWrapper.react",["fbt","FDSTooltip.react","GroupsCometCreatePreviewContext","react","stylex"],(function(a,b,c,d,e,f,g,h){"use strict";var i,j,k=j||(j=d("react")),l=j.useContext,m={container:{cursor:"x1h6gzvc",pointerEvents:"x67bb7w",$$css:!0},wrapper:{flexDirection:"xdt5ytf",pointerEvents:"x47corl",$$css:!0}};function a(a){var b=a.children;a.isPreview;a=a.xstyle;var d=h._("__JHASH__euOPr-ccO2a__JHASH__"),e=l(c("GroupsCometCreatePreviewContext"));e=e.isPreview;e=e===void 0?!1:e;return e?k.jsx("div",{className:(i||(i=c("stylex")))(m.container,a),children:k.jsx(c("FDSTooltip.react"),{align:"middle",tooltip:d,children:k.jsx("div",{className:"xdt5ytf x47corl",children:b})})}):b}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("GroupsCometNotificationSettingsEditDialog.entrypoint",["GroupsCometNotificationSettingsEditDialogQuery$Parameters","JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.groupID;return{queries:{notificationsSettingsQueryReference:{parameters:b("GroupsCometNotificationSettingsEditDialogQuery$Parameters"),variables:{groupID:a}}}}},root:c("JSResourceForInteraction")("GroupsCometNotificationSettingsEditDialog.react").__setRef("GroupsCometNotificationSettingsEditDialog.entrypoint")};g["default"]=a}),98);
__d("GroupsCometEntityMenuCollapseButtonBadge.react",["CometBadge.react","I64","MWChatBadgeCountUpdates.react","qex","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=h||d("react");function a(a){a=a.communityID;a=d("MWChatBadgeCountUpdates.react").useUnseenThreadCount((i||(i=d("I64"))).of_string(a));if(a==null||a===0)return null;return c("qex")._("268")?null:j.jsx(c("CometBadge.react"),{size:9})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("GroupsCometAboutPanelSettingsContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext({isIconFilled:!1});g["default"]=b}),98);
__d("GroupsCometManageNotificationsActionMenuItem.react",["fbt","ix","CometEntryPointDialogTrigger.react","CometMenuItem.react","GroupsCometAboutPanelSettingsContext","GroupsCometManageNotificationsActionMenuItem_group.graphql","GroupsCometNotificationSettingsEditDialog.entrypoint","fbicon","react"],(function(a,b,c,d,e,f,g,h,i){"use strict";var j,k,l=k||(k=d("react")),m=k.useContext;j!==void 0?j:j=b("GroupsCometManageNotificationsActionMenuItem_group.graphql");function a(a){var b=a.groupID,e=a.iconStyle,f=e===void 0?"normal":e,g=a.onPress;e=a.onSave;var j=a.primaryText,k=a.secondaryText;a=m(c("GroupsCometAboutPanelSettingsContext"));var n=a.isIconFilled;return l.jsx(c("CometEntryPointDialogTrigger.react"),{dialogEntryPoint:c("GroupsCometNotificationSettingsEditDialog.entrypoint"),otherProps:{onSave:e},preloadParams:{groupID:b},preloadTrigger:"button",children:function(a,b,e,m){return l.jsx(c("CometMenuItem.react"),{icon:n?d("fbicon")._(i("508241"),20):d("fbicon")._(i("508244"),20),iconStyle:f,onClick:function(){a(),g&&g.apply(void 0,arguments)},onHoverIn:b,onHoverOut:e,onPressIn:m,primaryText:(b=j)!=null?b:h._("__JHASH__4EcBzf2TGjm__JHASH__"),secondaryText:k,testid:void 0})}})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("createUseMutation_DEPRECATED",["CometRelay","Promise","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=(i||d("react")).useCallback;function a(a,c,e,f){return function(){var g=d("CometRelay").useRelayEnvironment();return j(function(i,j,k){return new(h||(h=b("Promise")))(function(b,h){return d("CometRelay").enqueueMutation(g,{mutation:a,onCompleted:function(a,c){c&&c.length?h(c):b(a)},onError:function(a){return h([a])},optimisticResponse:c?c(i,j,k):null,optimisticUpdater:e?e(i,j,k):null,updater:f?f(i,j,k):null,variables:babelHelpers["extends"]({input:i},j)})})},[g])}}g["default"]=a}),98);
__d("GroupCometShareGroupQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="6814931405209227"}),null);
__d("GroupsCometJoinedActionMenuQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="6210574665697817"}),null);
__d("GroupLeadersEngagementFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1743660");b=d("FalcoLoggerInternal").create("group_leaders_engagement",a);e=b;g["default"]=e}),98);
__d("GroupReelsPlinkClickedFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2745");b=d("FalcoLoggerInternal").create("group_reels_plink_clicked",a);e=b;g["default"]=e}),98);
__d("GroupsKeyCommandShortcutsFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2955");b=d("FalcoLoggerInternal").create("groups_key_command_shortcuts",a);e=b;g["default"]=e}),98);
__d("XCometGroupViewerContentPendingControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/groups/{idorvanity}/my_pending_content/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("GroupClickActionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("780");b=d("FalcoLoggerInternal").create("group_click_action",a);e=b;g["default"]=e}),98);